"""MetaTrader 5 Expert Advisor preset (.set) file generator."""

from __future__ import annotations

import os
from pathlib import Path
from typing import List

from src.config import AppConfig


class PresetGenerator:
    """Generates native .set preset files for LiveONNX-EA and DMatrix-EA."""

    def __init__(self, config: AppConfig, terminal_data_path: Path, common_path: Path):
        self.config = config
        self.terminal_data_path = terminal_data_path
        self.common_path = common_path

    def _bool_to_mql_str(self, val: bool) -> str:
        """Convert Python boolean to MQL5 .set boolean integer string (1 or 0)."""
        return "1" if val else "0"

    def build_live_preset_content(self) -> str:
        """Construct full parameter content for LiveONNX-EA .set preset."""
        cfg = self.config
        sym = cfg.symbol
        tf = cfg.clean_timeframe

        # LiveONNX-only parameters fallback strictly to LiveONNX-EA.mq5 defaults when not in env
        trade_dir = os.getenv("INP_TRADE_DIRECTION", "0")
        min_buy_env = os.getenv("INP_MINIMAL_LEVEL_ACCEPTED_BUY")
        if min_buy_env is not None:
            min_buy = min_buy_env
        elif cfg.eval_buy_classification_threshold is not None:
            min_buy = f"{cfg.eval_buy_classification_threshold:.2f}"
        elif cfg.eval_classification_threshold is not None:
            min_buy = f"{cfg.eval_classification_threshold:.2f}"
        else:
            min_buy = "0.50"

        min_sell_env = os.getenv("INP_MINIMAL_LEVEL_ACCEPTED_SELL")
        if min_sell_env is not None:
            min_sell = min_sell_env
        elif cfg.eval_sell_classification_threshold is not None:
            min_sell = f"{cfg.eval_sell_classification_threshold:.2f}"
        elif cfg.eval_classification_threshold is not None:
            min_sell = f"{cfg.eval_classification_threshold:.2f}"
        else:
            min_sell = "0.50"
        lot_size = os.getenv("INP_LOT_SIZE", "0.01")
        enable_sr = os.getenv("INP_ENABLE_SR_SNAPPING", "1")
        sr_bars = os.getenv("INP_SR_LOOKBACK_BARS", "12")
        sr_pivot_k = os.getenv("INP_SR_PIVOT_STRENGTH", "2")
        sr_offset = os.getenv("INP_SR_OFFSET_POINTS", "30")
        sr_mode = os.getenv("INP_SR_ZONE_SELECTION", "0")
        enable_risk = os.getenv("INP_ENABLE_RISK_FILTER", "1")
        enable_dyn_lot = os.getenv("INP_ENABLE_DYNAMIC_LOT_SIZING", "0")
        max_lot = os.getenv("INP_MAX_LOT_SIZE", "0.05")
        margin_multiplier = os.getenv("INP_MARGIN_SAFETY_MULTIPLIER", "1.5")
        max_rr_ratio = os.getenv("INP_MAX_RISK_REWARD_RATIO", "1.5")
        max_trade_risk_pct = os.getenv("INP_MAX_TRADE_RISK_PCT", "3.0")
        enable_cal = os.getenv("INP_ENABLE_CALENDAR_FILTER", "1")
        enable_news = os.getenv("INP_ENABLE_NEWS_FILTER", "1")
        risk_garch_horizon = os.getenv("INP_RISK_GARCH_HORIZON", str(cfg.garch_horizon))
        k_tp = os.getenv("INP_KTP", "1.5")
        k_sl = os.getenv("INP_KSL", "1.5")
        consecutive_mode = os.getenv("INP_CONSECUTIVE_MODE", "0")
        max_consec_orders = os.getenv("INP_MAX_CONSECUTIVE_ORDERS", "3")
        hurdle_profit_pct = os.getenv("INP_HURDLE_PROFIT_PCT", "50.0")
        profit_lock_pct = os.getenv("INP_PROFIT_LOCK_PCT", "50.0")
        anti_chop_displacement = os.getenv("INP_ANTI_CHOP_MIN_DISPLACEMENT", "150")
        safety_offset_points = os.getenv("INP_SAFETY_OFFSET_POINTS", "20")
        enable_swap_amort = os.getenv("INP_ENABLE_SWAP_AMORTIZATION", "1")
        consec_slot_filter = os.getenv("INP_CONSECUTIVE_SLOT_FILTER", "0")
        ignore_conflicting = os.getenv("INP_IGNORE_CONFLICTING_SIGNALS", "1")
        enable_opposing_filter = os.getenv("INP_ENABLE_OPPOSING_REGIME_FILTER", "0")
        opposing_streak = os.getenv("INP_OPPOSING_STREAK_THRESHOLD", "2")
        opposing_action = os.getenv("INP_OPPOSING_ACTION", "0")
        opposing_trailing_pts = os.getenv("INP_OPPOSING_TRAILING_POINTS", "50")
        opposing_recalc_ratio = os.getenv("INP_OPPOSING_RECALCULATE_RATIO", "0.5")
        ignore_audit = os.getenv("INP_IGNORE_AUDIT", "0")

        return f"""; MetaTrader 5 Expert Advisor Settings (.set)
; Auto-generated by MT5 MLOps Pipeline ({sym} {cfg.timeframe})
InpMagicNumber={cfg.magic_number}
InpTradeDirection={trade_dir}
InpMinimalLevelAcceptedBuy={min_buy}
InpMinimalLevelAcceptedSell={min_sell}
InpLotSize={lot_size}
InpConsecutiveMode={consecutive_mode}
InpMaxConsecutiveOrders={max_consec_orders}
InpHurdleProfitPct={hurdle_profit_pct}
InpProfitLockPct={profit_lock_pct}
InpAntiChopMinDisplacement={anti_chop_displacement}
InpSafetyOffsetPoints={safety_offset_points}
InpEnableSwapAmortization={enable_swap_amort}
InpConsecutiveSlotFilter={consec_slot_filter}
InpIgnoreConflictingSignals={ignore_conflicting}
InpEnableOpposingRegimeFilter={enable_opposing_filter}
InpOpposingStreakThreshold={opposing_streak}
InpOpposingAction={opposing_action}
InpOpposingTrailingPoints={opposing_trailing_pts}
InpOpposingRecalculateRatio={opposing_recalc_ratio}
InpIgnoreAudit={ignore_audit}
InpFeatureLookback={cfg.feature_lookback}
InpUseADX={self._bool_to_mql_str(cfg.use_adx)}
InpUseATR={self._bool_to_mql_str(cfg.use_atr)}
InpUseBands={self._bool_to_mql_str(cfg.use_bands)}
InpUseMACD={self._bool_to_mql_str(cfg.use_macd)}
InpUseFastMA={self._bool_to_mql_str(cfg.use_fast_ma)}
InpUseSlowMA={self._bool_to_mql_str(cfg.use_slow_ma)}
InpUseRSI={self._bool_to_mql_str(cfg.use_rsi)}
InpUseStochastic={self._bool_to_mql_str(cfg.use_stochastic)}
InpUseCandlestick={self._bool_to_mql_str(cfg.use_candlestick)}
InpUseTimestampWeek={self._bool_to_mql_str(cfg.use_timestamp_week)}
InpUseTimestampDay={self._bool_to_mql_str(cfg.use_timestamp_day)}
InpUseOpenMarkets={self._bool_to_mql_str(cfg.use_open_markets)}
InpUseSpread={self._bool_to_mql_str(cfg.use_spread)}
InpUseGarchFeatures={self._bool_to_mql_str(cfg.use_garch_features)}
InpGarchHorizon={cfg.garch_horizon}
InpPriceSize={cfg.price_size}
InpGarchAlpha={cfg.garch_alpha}
InpGarchBeta={cfg.garch_beta}
InpEnableSRSnapping={enable_sr}
InpSRLookbackBars={sr_bars}
InpSRPivotStrength={sr_pivot_k}
InpSROffsetPoints={sr_offset}
InpSRZoneSelection={sr_mode}
InpEnableRiskFilter={enable_risk}
InpEnableDynamicLotSizing={enable_dyn_lot}
InpMaxLotSize={max_lot}
InpMarginSafetyMultiplier={margin_multiplier}
InpMaxRiskRewardRatio={max_rr_ratio}
InpMaxTradeRiskPct={max_trade_risk_pct}
InpEnableCalendarFilter={enable_cal}
InpEnableNewsFilter={enable_news}
InpRiskGarchHorizon={risk_garch_horizon}
InpKTP={k_tp}
InpKSL={k_sl}
InpTradeMonday={self._bool_to_mql_str(cfg.trade_monday)}
InpMondayStartTime={cfg.trade_monday_start}
InpMondayEndTime={cfg.trade_monday_end}
InpTradeTuesday={self._bool_to_mql_str(cfg.trade_tuesday)}
InpTuesdayStartTime={cfg.trade_tuesday_start}
InpTuesdayEndTime={cfg.trade_tuesday_end}
InpTradeWednesday={self._bool_to_mql_str(cfg.trade_wednesday)}
InpWednesdayStartTime={cfg.trade_wednesday_start}
InpWednesdayEndTime={cfg.trade_wednesday_end}
InpTradeThursday={self._bool_to_mql_str(cfg.trade_thursday)}
InpThursdayStartTime={cfg.trade_thursday_start}
InpThursdayEndTime={cfg.trade_thursday_end}
InpTradeFriday={self._bool_to_mql_str(cfg.trade_friday)}
InpFridayStartTime={cfg.trade_friday_start}
InpFridayEndTime={cfg.trade_friday_end}
InpModelBuyPath=Models/{sym}_{tf}_model_buy.onnx
InpModelSellPath=Models/{sym}_{tf}_model_sell.onnx
InpADXPeriod={cfg.adx_period}
InpATRPeriod={cfg.atr_period}
InpBandsPeriod={cfg.bands_period}
InpBandsShift={cfg.bands_shift}
InpBandsDev={cfg.bands_dev}
InpBandsAppliedPrice={cfg.bands_applied_price}
InpMACDFastPeriod={cfg.macd_fast}
InpMACDSlowPeriod={cfg.macd_slow}
InpMACDSignalPeriod={cfg.macd_signal}
InpMACDAppliedPrice={cfg.macd_applied_price}
InpFastMAPeriod={cfg.fast_ma_period}
InpFastMAShift={cfg.fast_ma_shift}
InpFastMAMethod={cfg.fast_ma_method}
InpFastMAAppliedPrice={cfg.fast_ma_applied_price}
InpSlowMAPeriod={cfg.slow_ma_period}
InpSlowMAShift={cfg.slow_ma_shift}
InpSlowMAMethod={cfg.slow_ma_method}
InpSlowMAAppliedPrice={cfg.slow_ma_applied_price}
InpRSIPeriod={cfg.rsi_period}
InpRSIAppliedPrice={cfg.rsi_applied_price}
InpStochK={cfg.stoch_k}
InpStochD={cfg.stoch_d}
InpStochSlowing={cfg.stoch_slowing}
InpStochMethod={cfg.stoch_method}
InpStochPriceField={cfg.stoch_price_field}
"""

    def build_dmatrix_preset_content(self) -> str:
        """Construct full parameter content for DMatrix-EA .set preset."""
        cfg = self.config
        sym = cfg.symbol

        return f"""; MetaTrader 5 Expert Advisor Settings (.set)
; Auto-generated by MT5 MLOps Pipeline ({sym} {cfg.timeframe})
InpMagicNumber={cfg.magic_number}
InpLotSize=0.01
InpUseADX={self._bool_to_mql_str(cfg.use_adx)}
InpUseATR={self._bool_to_mql_str(cfg.use_atr)}
InpUseBands={self._bool_to_mql_str(cfg.use_bands)}
InpUseMACD={self._bool_to_mql_str(cfg.use_macd)}
InpUseFastMA={self._bool_to_mql_str(cfg.use_fast_ma)}
InpUseSlowMA={self._bool_to_mql_str(cfg.use_slow_ma)}
InpUseRSI={self._bool_to_mql_str(cfg.use_rsi)}
InpUseStochastic={self._bool_to_mql_str(cfg.use_stochastic)}
InpUseCandlestick={self._bool_to_mql_str(cfg.use_candlestick)}
InpUseTimestampWeek={self._bool_to_mql_str(cfg.use_timestamp_week)}
InpUseTimestampDay={self._bool_to_mql_str(cfg.use_timestamp_day)}
InpUseOpenMarkets={self._bool_to_mql_str(cfg.use_open_markets)}
InpUseSpread={self._bool_to_mql_str(cfg.use_spread)}
InpUseGarchFeatures={self._bool_to_mql_str(cfg.use_garch_features)}
InpFeatureLookback={cfg.feature_lookback}
InpGarchHorizon={cfg.garch_horizon}
InpPriceSize={cfg.price_size}
InpGarchAlpha={cfg.garch_alpha}
InpGarchBeta={cfg.garch_beta}
InpLabelHorizonBars={cfg.label_horizon_bars}
InpLabelMinPoints={cfg.label_min_points}
InpLabelMaxAdversePoints={cfg.label_max_adverse_points}
InpTradeMonday={self._bool_to_mql_str(cfg.trade_monday)}
InpMondayStartTime={cfg.trade_monday_start}
InpMondayEndTime={cfg.trade_monday_end}
InpTradeTuesday={self._bool_to_mql_str(cfg.trade_tuesday)}
InpTuesdayStartTime={cfg.trade_tuesday_start}
InpTuesdayEndTime={cfg.trade_tuesday_end}
InpTradeWednesday={self._bool_to_mql_str(cfg.trade_wednesday)}
InpWednesdayStartTime={cfg.trade_wednesday_start}
InpWednesdayEndTime={cfg.trade_wednesday_end}
InpTradeThursday={self._bool_to_mql_str(cfg.trade_thursday)}
InpThursdayStartTime={cfg.trade_thursday_start}
InpThursdayEndTime={cfg.trade_thursday_end}
InpTradeFriday={self._bool_to_mql_str(cfg.trade_friday)}
InpFridayStartTime={cfg.trade_friday_start}
InpFridayEndTime={cfg.trade_friday_end}
InpAvoidPandemicTime={self._bool_to_mql_str(cfg.avoid_pandemictime)}
InpPandemicStartTime={cfg.pandemic_start_date}
InpPandemicEndTime={cfg.pandemic_end_date}
InpADXPeriod={cfg.adx_period}
InpATRPeriod={cfg.atr_period}
InpBandsPeriod={cfg.bands_period}
InpBandsShift={cfg.bands_shift}
InpBandsDev={cfg.bands_dev}
InpBandsAppliedPrice={cfg.bands_applied_price}
InpMACDFastPeriod={cfg.macd_fast}
InpMACDSlowPeriod={cfg.macd_slow}
InpMACDSignalPeriod={cfg.macd_signal}
InpMACDAppliedPrice={cfg.macd_applied_price}
InpFastMAPeriod={cfg.fast_ma_period}
InpFastMAShift={cfg.fast_ma_shift}
InpFastMAMethod={cfg.fast_ma_method}
InpFastMAAppliedPrice={cfg.fast_ma_applied_price}
InpSlowMAPeriod={cfg.slow_ma_period}
InpSlowMAShift={cfg.slow_ma_shift}
InpSlowMAMethod={cfg.slow_ma_method}
InpSlowMAAppliedPrice={cfg.slow_ma_applied_price}
InpRSIPeriod={cfg.rsi_period}
InpRSIAppliedPrice={cfg.rsi_applied_price}
InpStochK={cfg.stoch_k}
InpStochD={cfg.stoch_d}
InpStochSlowing={cfg.stoch_slowing}
InpStochMethod={cfg.stoch_method}
InpStochPriceField={cfg.stoch_price_field}
"""

    def generate_all(self, target_dirs: List[Path] | None = None) -> Path:
        """Write LiveONNX preset file strictly scoped to Symbol and Timeframe."""
        if target_dirs is None:
            target_dirs = [
                self.terminal_data_path / "MQL5" / "Presets",
                self.common_path / "Files" / "Presets",
            ]

        sym = self.config.symbol
        tf = self.config.clean_timeframe

        live_filename = f"LiveONNX-EA_{sym}_{tf}.set"
        live_content = self.build_live_preset_content()

        primary_live: Path | None = None

        for directory in target_dirs:
            directory.mkdir(parents=True, exist_ok=True)
            p_live = directory / live_filename

            with open(p_live, "w", encoding="utf-8") as f:
                f.write(live_content)

            if primary_live is None:
                primary_live = p_live

            print(f"    [+] Saved preset (.set): {p_live}")

        print(f"[+] Preset generation complete: '{live_filename}'")
        assert primary_live is not None
        return primary_live
